webtalk_init -webtalk_dir D:/Desktop/200T_workspace/KX7A200/KX7A100.sim/sim_1/behav/xsim/xsim.dir/uart_fft_bridge_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 18 16:36:41 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f81a7188-eca9-4620-b8f6-40d922a2b2a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a95f77dec39049b5ac4ddca68a042d67" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 6800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "166535 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "10.70_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "44540_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2406599817 -regid "" -xml D:/Desktop/200T_workspace/KX7A200/KX7A100.sim/sim_1/behav/xsim/xsim.dir/uart_fft_bridge_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Desktop/200T_workspace/KX7A200/KX7A100.sim/sim_1/behav/xsim/xsim.dir/uart_fft_bridge_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Desktop/200T_workspace/KX7A200/KX7A100.sim/sim_1/behav/xsim/xsim.dir/uart_fft_bridge_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
