set_property SRC_FILE_INFO {cfile:D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/constrs_1/new/KX7A100_PIN.xdc rfile:../../../KX7A100.srcs/constrs_1/new/KX7A100_PIN.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19  IOSTANDARD LVCMOS15} [get_ports iw_SYS_CLK]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D17  IOSTANDARD LVCMOS15} [get_ports io_CLK[0] ]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C18  IOSTANDARD LVCMOS15} [get_ports io_CLK[1] ]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F21  IOSTANDARD LVCMOS15} [get_ports iw_UART_RX]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F15  IOSTANDARD LVCMOS15} [get_ports ow_UART_TX]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L6   IOSTANDARD LVCMOS25} [get_ports ow_EEPROM_IIC_SCL]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M5   IOSTANDARD LVCMOS25} [get_ports io_EEPROM_IIC_SDA]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P6   IOSTANDARD LVCMOS25} [get_ports ow_LED_PIN ]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17  IOSTANDARD LVCMOS33} [get_ports ow_WS2812B ]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M6   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[0] ]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T3   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[1] ]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[2] ]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J4   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[3] ]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J5   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[4] ]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J2   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[5] ]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H5   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[6] ]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F4   IOSTANDARD LVCMOS25} [get_ports ow_SMG_DIG[7] ]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W4   IOSTANDARD LVCMOS25} [get_ports ow_SMG_SEL[0] ]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V5   IOSTANDARD LVCMOS25} [get_ports ow_SMG_SEL[1] ]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J16  IOSTANDARD LVCMOS15} [get_ports iw_KEY_PIN ]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS15} [get_ports phy_rst_o]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V4   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rxc    ]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R6   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rx_ctl ]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T6   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rxd[0] ]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U7   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rxd[1] ]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V8   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rxd[2] ]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V9   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rxd[3] ]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W5   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_txc    ]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R3   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_tx_ctl ]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W6   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_txd[0] ]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U6   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_txd[1] ]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N5   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_txd[2] ]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R2   IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_txd[3] ]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V22  IOSTANDARD LVCMOS15} [get_ports ow_FMC_SCL]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P20  IOSTANDARD LVCMOS15} [get_ports io_FMC_SDA]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19  IOSTANDARD LVCMOS15} [get_ports io_FMC_PRSNT  ]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R19  IOSTANDARD LVCMOS15} [get_ports io_FMC_PG_M2C ]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18  IOSTANDARD LVCMOS15} [get_ports io_FMC_PG_C2M ]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17  IOSTANDARD LVCMOS15} [get_ports io_FMC_RES[0] ]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N15  IOSTANDARD LVCMOS15} [get_ports io_FMC_RES[1] ]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H4   IOSTANDARD LVCMOS25} [get_ports io_FMC_clk_p[0] ]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G4   IOSTANDARD LVCMOS25} [get_ports io_FMC_clk_n[0] ]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 0] ]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 0] ]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 1] ]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 1] ]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 2] ]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 2] ]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 3] ]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 3] ]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 4] ]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 4] ]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 5] ]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 5] ]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 6] ]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 6] ]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 7] ]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 7] ]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 8] ]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 8] ]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K6   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[ 9] ]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J6   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[ 9] ]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[10] ]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[10] ]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N4   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[11] ]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[11] ]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L5   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[12] ]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L4   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[12] ]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[13] ]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[13] ]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[14] ]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[14] ]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P5   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[15] ]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P4   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[15] ]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[16] ]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[16] ]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R4   IOSTANDARD LVCMOS25} [get_ports io_FMC_clk_p[1] ]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T4   IOSTANDARD LVCMOS25} [get_ports io_FMC_clk_n[1] ]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T5   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[17] ]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U5   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[17] ]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y4   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[18] ]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA4  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[18] ]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V7   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[19] ]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W7   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[19] ]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[20] ]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[20] ]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[21] ]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[21] ]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[22] ]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[22] ]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[23] ]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U1   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[23] ]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y6   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[24] ]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA6  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[24] ]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y3   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[25] ]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA3  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[25] ]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[26] ]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y2   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[26] ]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA1  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[27] ]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB1  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[27] ]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB3  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[28] ]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB2  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[28] ]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y8   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[29] ]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y7   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[29] ]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB7  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[30] ]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB6  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[30] ]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA5  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[31] ]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB5  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[31] ]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W9   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[32] ]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y9   IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[32] ]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA8  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_p[33] ]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB8  IOSTANDARD LVCMOS25} [get_ports io_FMC_LA_n[33] ]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U16  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 0] ]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 1] ]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 2] ]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 3] ]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V14  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 4] ]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 5] ]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 6] ]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 7] ]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 8] ]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[ 9] ]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[10] ]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W12  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[11] ]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[12] ]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y12  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[13] ]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[14] ]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[15] ]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[16] ]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U15  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[17] ]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[18] ]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W15  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[19] ]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V13  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[20] ]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[21] ]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[22] ]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[23] ]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[24] ]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[25] ]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y13  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[26] ]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W11  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[27] ]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[28] ]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[29] ]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[30] ]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA9  IOSTANDARD LVCMOS33} [get_ports ow_TEST_PIN[31] ]
