# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.srcs/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk.xci
# IP: The module: 'clk_wiz_mclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_mclk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_mclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_mclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.srcs/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk.xci
# IP: The module: 'clk_wiz_mclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_mclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_mclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_mclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
