################################ NET - IOSTANDARD ################################
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.5 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
################################ SPI Configurate Setting ################################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
################################ clock and reset define ################################
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS15} [get_ports iw_SYS_CLK]

set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS15} [get_ports {io_CLK[0]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS15} [get_ports {io_CLK[1]}]
################################ usb uart define ################################
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS15} [get_ports iw_UART_RX]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS15} [get_ports ow_UART_TX]
################################ EEPROM IIC define ################################
set_property -dict {PACKAGE_PIN L6 IOSTANDARD LVCMOS25} [get_ports ow_EEPROM_IIC_SCL]
set_property -dict {PACKAGE_PIN M5 IOSTANDARD LVCMOS25} [get_ports io_EEPROM_IIC_SDA]
################################ LED_pin ################################
set_property -dict {PACKAGE_PIN P6 IOSTANDARD LVCMOS25} [get_ports ow_LED_PIN]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports ow_WS2812B]
################################ SMG_pin ################################
set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[0]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[1]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[2]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[3]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[4]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[5]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[6]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_DIG[7]}]

set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_SEL[0]}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS25} [get_ports {ow_SMG_SEL[1]}]
################################ KEY_pin ################################
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS15} [get_ports iw_KEY_PIN]
################################ PHYA ################################
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS15} [get_ports phy_rst_o]
### -----------------RX------------------###
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rxc]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_rx_ctl]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_rxd[0]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_rxd[1]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_rxd[2]}]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_rxd[3]}]
### -----------------TX------------------###
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_txc]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS25} [get_ports PHYA_rgmii_tx_ctl]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_txd[0]}]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_txd[1]}]
set_property -dict {PACKAGE_PIN N5 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_txd[2]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS25} [get_ports {PHYA_rgmii_txd[3]}]

set_property SLEW FAST [get_ports PHYA_rgmii_txc]
set_property SLEW FAST [get_ports PHYA_rgmii_tx_ctl]
set_property SLEW FAST [get_ports {PHYA_rgmii_txd[*]}]
################################ EEPROM IIC define ################################
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS15} [get_ports ow_FMC_SCL]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS15} [get_ports io_FMC_SDA]

set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS15} [get_ports io_FMC_PRSNT]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS15} [get_ports io_FMC_PG_M2C]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS15} [get_ports io_FMC_PG_C2M]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS15} [get_ports {io_FMC_RES[0]}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS15} [get_ports {io_FMC_RES[1]}]

set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_clk_p[0]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_clk_n[0]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[0]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[0]}]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[1]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[1]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[2]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[2]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[3]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[4]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[4]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[5]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[5]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[6]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[6]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[7]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[7]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[8]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[8]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[9]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[9]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[10]}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[10]}]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[11]}]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[11]}]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[12]}]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[12]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[13]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[13]}]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[14]}]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[14]}]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[15]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[15]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[16]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[16]}]

set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_clk_p[1]}]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_clk_n[1]}]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[17]}]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[17]}]
set_property -dict {PACKAGE_PIN Y4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[18]}]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[18]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[19]}]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[19]}]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[20]}]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[20]}]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[21]}]
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[21]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[22]}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[22]}]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[23]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[23]}]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[24]}]
set_property -dict {PACKAGE_PIN AA6 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[24]}]
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[25]}]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[25]}]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[26]}]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[26]}]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[27]}]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[27]}]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[28]}]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[28]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[29]}]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[29]}]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[30]}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[30]}]
set_property -dict {PACKAGE_PIN AA5 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[31]}]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[31]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[32]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[32]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_p[33]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS25} [get_ports {io_FMC_LA_n[33]}]
################################ test_pin ################################
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[0]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[1]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[2]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[3]}]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[4]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[5]}]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[6]}]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[7]}]

set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[8]}]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[9]}]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[10]}]
set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[11]}]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[12]}]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[13]}]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[14]}]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[15]}]

set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[16]}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[17]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[18]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[19]}]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[20]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[21]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[22]}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[23]}]

set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[24]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[25]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[26]}]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[27]}]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[28]}]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[29]}]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[30]}]
set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVCMOS33} [get_ports {ow_TEST_PIN[31]}]

create_clock -period 20.000 -name iw_SYS_CLK -waveform {0.000 10.000} [get_ports iw_SYS_CLK]

create_generated_clock -name clk_div_0 -source [get_pins mclk_rst_module_inst/clk_div_module_inst0/iw_sys_clk] -divide_by 4 [get_pins mclk_rst_module_inst/clk_div_module_inst0/clk_div]
create_generated_clock -name clk_div_1 -source [get_pins mclk_rst_module_inst/clk_div_module_inst1/iw_sys_clk] -divide_by 2 [get_pins mclk_rst_module_inst/clk_div_module_inst1/clk_div]
create_generated_clock -name clk_div_2 -source [get_pins mclk_rst_module_inst/clk_div_module_inst2/iw_sys_clk] -divide_by 20 [get_pins mclk_rst_module_inst/clk_div_module_inst2/clk_div]
create_generated_clock -name clk_div_3 -source [get_pins mclk_rst_module_inst/clk_div_module_inst3/iw_sys_clk] -divide_by 100 [get_pins mclk_rst_module_inst/clk_div_module_inst3/clk_div]
create_generated_clock -name clk_div_4 -source [get_pins mclk_rst_module_inst/clk_div_module_inst4/iw_sys_clk] -divide_by 250 [get_pins mclk_rst_module_inst/clk_div_module_inst4/clk_div]
create_generated_clock -name clk_div_5 -source [get_pins mclk_rst_module_inst/clk_div_module_inst5/iw_sys_clk] -divide_by 100 [get_pins mclk_rst_module_inst/clk_div_module_inst5/clk_div]
create_generated_clock -name clk_div_6 -source [get_pins mclk_rst_module_inst/clk_div_module_inst6/iw_sys_clk] -divide_by 10000 [get_pins mclk_rst_module_inst/clk_div_module_inst6/clk_div]

