# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.srcs/sources_1/ip/fifo_72x512/fifo_72x512.xci
# IP: The module: 'fifo_72x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_72x512'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_72x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_72x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.srcs/sources_1/ip/fifo_72x512/fifo_72x512.xci
# IP: The module: 'fifo_72x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_72x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_72x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_72x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
