# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/KX7A100_PIN.xdc

# XDC: new/ila.xdc

# IP: ip/ila_eth_rx/ila_eth_rx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_eth_rx || ORIG_REF_NAME==ila_eth_rx} -quiet] -quiet
