# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Desktop/200T_workspace/KX7A200/KX7A100.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Desktop/200T_workspace/KX7A200/KX7A100.cache/wt [current_project]
set_property parent.project_path D:/Desktop/200T_workspace/KX7A200/KX7A100.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Desktop/200T_workspace/KX7A200/KX7A100.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/uiudp_stack.dcp
set_property used_in_implementation false [get_files D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/uiudp_stack.dcp]
read_verilog -library xil_defaultlib {
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/dna_rtl/Unix_Epoch_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/mclk_rtl/clk_div_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/Crossclock_rtl/cmd_cov_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/ddr3_app_rtl/ddr3_cache_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/ddr3_app_rtl/ddr3_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/ddr3_udp_read_bridge.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/dna_rtl/dna_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/mclk_rtl/edge_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/IIC_rtl/eeprom_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/IIC_rtl/iic_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/key_rtl/key.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/key_rtl/key_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/led_rtl/led_alternating_flicker_drive.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/led_rtl/led_flicker_drive.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/led_rtl/led_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/led_rtl/led_pwm_drive.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/led_rtl/led_run_drive.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/master_wrapper.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/mclk_rtl/mclk_rst_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/mclk_rtl/reset_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/uart_rtl/rx.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/smg_rtl/smg_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/test_data_generator_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_axi_lite_sm.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_example_design_resets.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_reset_sync.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_sync_block.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/uart_rtl/tx.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/uart_rtl/uart_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/uart_rtl/uart_rx.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/uart_rtl/uart_tx.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/udp_64x4096_fifo.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/udp_ddr3_write_bridge.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/udp_rtl/udp_drive.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/led_rtl/ws2812b_module.v
  D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/new/top.v
}
read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/ila_eth_rx/ila_eth_rx.xci
set_property used_in_synthesis false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_rx/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_rx/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_rx/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_rx/ila_eth_rx_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/vio_dna/vio_dna.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/vio_dna/vio_dna.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/vio_dna/vio_dna_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/fifo_bits_cov/fifo_bits_cov.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_bits_cov/fifo_bits_cov.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_bits_cov/fifo_bits_cov_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_bits_cov/fifo_bits_cov_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/fifo_ddr3_rd/fifo_ddr3_rd.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_ddr3_rd/fifo_ddr3_rd.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_ddr3_rd/fifo_ddr3_rd_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_ddr3_rd/fifo_ddr3_rd_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/fifo_72x512/fifo_72x512.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/axis_dwidth_converter_1/axis_dwidth_converter_1.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/axis_dwidth_converter_1/axis_dwidth_converter_1_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/fifo_bit_cov/fifo_bit_cov.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_bit_cov/fifo_bit_cov.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_bit_cov/fifo_bit_cov_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_bit_cov/fifo_bit_cov_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/uart_fifo/uart_fifo.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/uart_fifo/uart_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/uart_fifo/uart_fifo_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/fifo_ddr3_wr/fifo_ddr3_wr.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_ddr3_wr/fifo_ddr3_wr.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_ddr3_wr/fifo_ddr3_wr_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/fifo_ddr3_wr/fifo_ddr3_wr_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/ila_fft_debug/ila_fft_debug.xci
set_property used_in_synthesis false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_fft_debug/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_fft_debug/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_fft_debug/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_fft_debug/ila_fft_debug_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/vio_fft_debug/vio_fft_debug.xci
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/vio_fft_debug/vio_fft_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/vio_fft_debug/vio_fft_debug_ooc.xdc]

read_ip -quiet D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/sources_1/ip/ila_eth_system/ila_eth_system.xci
set_property used_in_synthesis false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_system/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_system/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_system/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/200T_workspace/KX7A200/KX7A100.gen/sources_1/ip/ila_eth_system/ila_eth_system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/constrs_1/new/KX7A100_PIN.xdc
set_property used_in_implementation false [get_files D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/constrs_1/new/KX7A100_PIN.xdc]

read_xdc D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/constrs_1/new/ila.xdc
set_property used_in_implementation false [get_files D:/Desktop/200T_workspace/KX7A200/KX7A100.srcs/constrs_1/new/ila.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a200tfbg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
