######################################################################
#
# File name : uart_fft_ifft_bridge_tb_compile.do
# Created on: Sun Sep 20 13:55:47 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../KX7A100.gen/sources_1/ip/xfft_0/sim/xfft_0.vhd" \

vlog  -incr -work xil_defaultlib  \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/uart_fft_ifft_bridge_module.v" \
"../../../../KX7A100.srcs/sim_1/new/uart_fft_ifft_bridge_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

######################################################################
#
# File name : uart_fft_ifft_bridge_tb_simulate.do
# Created on: Sun Sep 20 13:55:52 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xbip_utils_v3_0_10 -L axi_utils_v2_0_6 -L c_reg_fd_v12_0_6 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_6 -L xbip_dsp48_addsub_v3_0_6 -L xbip_addsub_v3_0_6 -L c_addsub_v12_0_14 -L c_mux_bit_v12_0_6 -L c_shift_ram_v12_0_14 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_16 -L cmpy_v6_0_19 -L floating_point_v7_0_18 -L xfft_v9_1_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.uart_fft_ifft_bridge_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1
######################################################################
# user config 
# Created date: 2026/9/20 14:2:1
######################################################################
#log 全部波形数据
log -r /*       
#设置数值显示的方式  eage: radix [-binary | -octal | -decimal | -unsigned | -ascii | time] | -showbase | -symbolic]
radix hex 
#打开wave窗口
view wave
#显示结构
view structure
#显示信号
view signals
# 运行保存的波形文件
do wave.do
#运行时间
run 10ms
