######################################################################
#
# File name : top_compile.do
# Created on: Fri Sep 18 14:46:59 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  \
"../../../../KX7A100.gen/sources_1/ip/vio_FMC/vio_FMC_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/fifo_bits_cov/fifo_bits_cov_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_std.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0_mig_sim.v" \
"../../../../KX7A100.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0.v" \
"../../../../KX7A100.gen/sources_1/ip/fifo_bit_cov/fifo_bit_cov_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/fifo_ddr3_rd/fifo_ddr3_rd_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/fifo_ddr3_wr/fifo_ddr3_wr_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/uart_fifo/uart_fifo_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/axis_dwidth_converter_1/axis_dwidth_converter_1_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/fifo_72x512/fifo_72x512_sim_netlist.v" \

vcom  -93 -work xil_defaultlib  \
"../../../../KX7A100.gen/sources_1/ip/xfft_0/sim/xfft_0.vhd" \

vlog  -incr -work xil_defaultlib  \
"../../../../KX7A100.gen/sources_1/ip/vio_dna/vio_dna_sim_netlist.v" \
"../../../../KX7A100.gen/sources_1/ip/clk_wiz_mclk/clk_wiz_mclk_sim_netlist.v" \
"../../../../KX7A100.srcs/sources_1/new/dna_rtl/Unix_Epoch_module.v" \
"../../../../KX7A100.srcs/sources_1/new/mclk_rtl/clk_div_module.v" \
"../../../../KX7A100.srcs/sources_1/new/Crossclock_rtl/cmd_cov_module.v" \
"../../../../KX7A100.srcs/sources_1/new/ddr3_app_rtl/ddr3_cache_module.v" \
"../../../../KX7A100.srcs/sources_1/new/ddr3_app_rtl/ddr3_module.v" \
"../../../../KX7A100.srcs/sources_1/new/dna_rtl/dna_module.v" \
"../../../../KX7A100.srcs/sources_1/new/mclk_rtl/edge_module.v" \
"../../../../KX7A100.srcs/sources_1/new/IIC_rtl/eeprom_module.v" \
"../../../../KX7A100.srcs/sources_1/new/IIC_rtl/iic_module.v" \
"../../../../KX7A100.srcs/sources_1/new/key_rtl/key.v" \
"../../../../KX7A100.srcs/sources_1/new/key_rtl/key_module.v" \
"../../../../KX7A100.srcs/sources_1/new/led_rtl/led_alternating_flicker_drive.v" \
"../../../../KX7A100.srcs/sources_1/new/led_rtl/led_flicker_drive.v" \
"../../../../KX7A100.srcs/sources_1/new/led_rtl/led_module.v" \
"../../../../KX7A100.srcs/sources_1/new/led_rtl/led_pwm_drive.v" \
"../../../../KX7A100.srcs/sources_1/new/led_rtl/led_run_drive.v" \
"../../../../KX7A100.srcs/sources_1/new/udp_rtl/master_wrapper.v" \
"../../../../KX7A100.srcs/sources_1/new/mclk_rtl/mclk_rst_module.v" \
"../../../../KX7A100.srcs/sources_1/new/mclk_rtl/reset_module.v" \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/rx.v" \
"../../../../KX7A100.srcs/sources_1/new/smg_rtl/smg_module.v" \
"../../../../KX7A100.srcs/sources_1/new/test_data_generator_module.v" \
"../../../../KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_axi_lite_sm.v" \
"../../../../KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_example_design_resets.v" \
"../../../../KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_reset_sync.v" \
"../../../../KX7A100.srcs/sources_1/new/udp_rtl/tri_mode_ethernet_mac_0_sync_block.v" \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/tx.v" \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/uart_data_loopback_module.v" \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/uart_fft_bridge_module.v" \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/uart_module.v" \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/uart_rx.v" \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/uart_tx.v" \
"../../../../KX7A100.srcs/sources_1/new/udp_rtl/udp_64x4096_fifo.v" \
"../../../../KX7A100.srcs/sources_1/new/udp_rtl/udp_drive.v" \
"../../../../KX7A100.srcs/sources_1/new/led_rtl/ws2812b_module.v" \
"../../../../KX7A100.srcs/sources_1/new/top.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

