######################################################################
#
# File name : uart_fft_ifft_bridge_tb_compile.do
# Created on: Sun Sep 20 13:55:47 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../KX7A100.gen/sources_1/ip/xfft_0/sim/xfft_0.vhd" \

vlog  -incr -work xil_defaultlib  \
"../../../../KX7A100.srcs/sources_1/new/uart_rtl/uart_fft_ifft_bridge_module.v" \
"../../../../KX7A100.srcs/sim_1/new/uart_fft_ifft_bridge_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

