######################################################################
#
# File name : uart_fft_bridge_tb_wave.do
# Created on: Fri Sep 18 14:52:08 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
