######################################################################
#
# File name : uart_fft_ifft_bridge_tb_wave.do
# Created on: Sun Sep 20 13:55:52 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
