# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.srcs/sources_1/ip/uart_fifo/uart_fifo.xci
# IP: The module: 'uart_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/uart_fifo/uart_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/uart_fifo/uart_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.srcs/sources_1/ip/uart_fifo/uart_fifo.xci
# IP: The module: 'uart_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/uart_fifo/uart_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/FPGA_RTL/KX7A100/KX7A200/KX7A100.gen/sources_1/ip/uart_fifo/uart_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
